name: "mnist"
data {
  name: "train_data"
  file_pattern: "/home/feng/data/mnist/train.npy"
  size: 50000
  dimensions: 784
}

data {
  name: "train_labels"
  file_pattern: "/home/feng/data/mnist/train_labels.npy"
  size: 50000
  dimensions: 1
  num_labels: 10
}

data {
  name: "validation_data"
  file_pattern: "/home/feng/data/mnist/validation.npy"
  size: 10000
  dimensions: 784
}

data {
  name: "validation_labels"
  file_pattern: "/home/feng/data/mnist/validation_labels.npy"
  size: 10000
  dimensions: 1
  num_labels: 10
}

data {
  name: "test_data"
  file_pattern: "/home/feng/data/mnist/test.npy"
  size: 10000
  dimensions: 784
}

data {
  name: "test_labels"
  file_pattern: "/home/feng/data/mnist/test_labels.npy"
  size: 10000
  dimensions: 1
  num_labels: 10
}

gpu_memory: "4G"
main_memory: "10G"
