optimizer: CD
stopcondition {
  all_processed: false
  steps: 20000
}
train: true
batchsize: 100
data_proto: "text_rbm1_LAST/data.pbtxt"
eval_after: 1000
checkpoint_after: 20000
checkpoint_directory: "/home/feng/data/multimodal_icml2013/rbm_models"
randomize: true
data_proto_prefix: "/home/feng/data/multimodal_icml2013/rbm_reps"
